Update Chinese translation for Lookup Anything
Pathoschild/LookupAnything pull request #885
Opened 2024-04-04 09:09 UTC by fjf010223

Update Translation of new vanilla fishing locations, including SVE and RSV fishing locations

2024-04-06 12:00 UTC, mc-kaishixiaxue requested changes
Line 660-661 have not yet been translated.
```
    "tree.name.mossy": "Mossy Tree", // TODO
    "tree.name.mystic": "Mystic Tree", // TODO
```
suggestion:
```
    "tree.name.mossy": "长满苔藓的树",
    "tree.name.mystic": "神秘树",
```

2024-04-08 03:41 UTC, Pathoschild approved these changes

2024-04-08 03:48 UTC, merged

2024-04-08 03:48 UTC, Pathoschild commented
Thanks for the help! Merged into `develop` for the upcoming Lookup Anything 1.41.5 (including @mc-kaishixiaxue's translations).

Unfortunately I removed the translations for Ridgeside Village and Stardew Valley Expanded locations. Maintaining translations for other mods is out of scope for this mod; I suggest submitting the translations to those mods' authors instead, since Lookup Anything will use the location's display name if it's set.

2024-04-08 06:07 UTC, fjf010223 commented
Oh, thank you for your hard work. I am sure there is a complete Chinese translation for the locations of SVE and RSV, but when using Lookup Anything to check the fish added by these mods, the mod locations in the spawn rule still display the code names, such as "Custom_Highlands" instead of "高地".
it's okay, I just provided translations for my friends and I think maybe more Chinese players need these translations.